language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install tox-travis

sudo: false

matrix:
  include:
    - name: Code Checks
      python: 3.6
      stage: linters
      env: TOXENV=code-linters

script: tox
